# Copyright (C) Microsoft Corporation. All rights reserved.
# Generates version files from version.txt

param(
    [string]$GitDescribe = ""
)

$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Read the version.txt content
$versionTxtPath = Join-Path $scriptDir "version.txt"
$versionTxtContent = (Get-Content $versionTxtPath -First 1).Trim()

# Split the 4 numbers that make up the version
$fileVersion = $versionTxtContent.Split(".")
$major = $fileVersion[0]
$minor = $fileVersion[1]
$patch = $fileVersion[2]
$build = if ($fileVersion.Count -gt 3) { $fileVersion[3] } else { "0" }

$versionString = "{0}.{1}.{2}.{3}" -f $major, $minor, $patch, $build
$versionStringShort = "{0}.{1}.{2}" -f $major, $minor, $patch

# If GitDescribe not provided, try to get it
if (-not $GitDescribe) {
    $repoRoot = Split-Path -Parent $scriptDir
    Push-Location $repoRoot
    try {
        $GitDescribe = git describe --tags --always 2>$null
        if (-not $GitDescribe) {
            $GitDescribe = git rev-parse --short HEAD 2>$null
        }
    } catch {
        $GitDescribe = "unknown"
    }
    Pop-Location
}

Write-Host "Version: $versionString"
Write-Host "Git: $GitDescribe"

# Generate the C header version file
$versionHContent = @"
// Copyright (C) Microsoft Corporation. All rights reserved.
// This file is generated by gen_version_files.ps1 - do not edit by hand

#define VLD_VERSION_MAJOR $major
#define VLD_VERSION_MINOR $minor
#define VLD_VERSION_PATCH $patch
#define VLD_VERSION_BUILD $build

#define VLD_VERSION $major, $minor, $patch, $build
#define VLD_VERSION_STRING "$versionString"
#define VLD_VERSION_STRING_SHORT "$versionStringShort"
#define VLD_GIT_DESCRIBE "$GitDescribe"
"@

$versionHPath = Join-Path $scriptDir "version.h"
$versionHContent | Out-File -FilePath $versionHPath -Encoding ASCII -NoNewline
Write-Host "Generated: $versionHPath"

# Generate version.props for MSBuild
$versionPropsContent = @"
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VldVersion>$versionString</VldVersion>
    <VldVersionShort>$versionStringShort</VldVersionShort>
    <VldGitDescribe>$GitDescribe</VldGitDescribe>
  </PropertyGroup>
</Project>
"@

$versionPropsPath = Join-Path $scriptDir "version.props"
$versionPropsContent | Out-File -FilePath $versionPropsPath -Encoding ASCII -NoNewline
Write-Host "Generated: $versionPropsPath"

# Generate version.iss for Inno Setup
$versionIssContent = @"
; Copyright (C) Microsoft Corporation. All rights reserved.
; This file is generated by gen_version_files.ps1 - do not edit by hand

#define VLD_VERSION_MAJOR "$major"
#define VLD_VERSION_MINOR "$minor"
#define VLD_VERSION_PATCH "$patch"
#define VLD_VERSION_BUILD "$build"
#define VLD_VERSION "$versionString"
#define VLD_VERSION_SHORT "$versionStringShort"
#define VLD_GIT_DESCRIBE "$GitDescribe"
"@

$versionIssPath = Join-Path $scriptDir "version.iss"
$versionIssContent | Out-File -FilePath $versionIssPath -Encoding ASCII -NoNewline
Write-Host "Generated: $versionIssPath"

Write-Host "Version files generated successfully."
